server:
  port: 8086

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adhyanchawla/hotel-microservice-config
          default-label: master
          clone-on-start: true
  profiles:
    active: dev